[project]
authors = ["Frank Loesche <loeschef@janelia.hhmi.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "G4.1-ArenaController"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
platformio = ">=6.1.16,<7"
